### ISSUE TITLE
Error invoking callback

### ISSUE THREAD

**Issue by trollollol123** [charliethomson/DeathmatchPlugin#4]
17:33:50 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: GenericArguments[0], 'T', on 'CounterStrikeSharp.API.Modules.Utils.CHandle`1[T]' violates the constraint of type parameter 'T'.
   at DeathmatchPlugin.Extensions.HandleExtensions.GetValueOrNull[T]
   at DeathmatchPlugin.Extensions.PlayerExtensions.ActiveWeapon(CCSPlayerController player) in C:\Program Files\dotnet\DeathmatchPlugin-1.0.2\DeathmatchPlugin\Extensions\PlayerExtensions.cs:line 106
   at DeathmatchPlugin.Effects.RefillPlayerAmmo.Do(CCSPlayerController player) in C:\Program Files\dotnet\DeathmatchPlugin-1.0.2\DeathmatchPlugin\Effects\RefillPlayerAmmo.cs:line 20
   at DeathmatchPlugin.DeathmatchPlugin.OnPlayerDeath(EventPlayerDeath event, GameEventInfo info) in C:\Program Files\dotnet\DeathmatchPlugin-1.0.2\DeathmatchPlugin\DeathmatchPlugin.cs:line 137
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by PatricNox** [comment]
Yes, latest CSSharp plugin API DLL doesnt work
